#
# Copyright (C) 2020 Wind River Systems, Inc.
#

# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend \
	${LAYERDIR}/classes/*.bbclass"

BBFILES_DYNAMIC += "\
    openembedded-layer:${LAYERDIR}/dynamic-layers/meta-oe/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "wr-nxp-s32g"
BBFILE_PATTERN_wr-nxp-s32g= "^${LAYERDIR}/"
BBFILE_PRIORITY_wr-nxp-s32g = "7"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_wr-nxp-s32g = "1"

LAYERDEPENDS_wr-nxp-s32g = "core wrlinux meta-arm networking-layer"
LAYERSERIES_COMPAT_wr-nxp-s32g = "wrl walnascar"

NON_MULTILIB_RECIPES:append = " u-boot-s32"
NON_MULTILIB_RECIPES:append = " atf-s32g"
NON_MULTILIB_RECIPES:append = " libfci"
NON_MULTILIB_RECIPES:append = " libfci-cli"

LAYER_PATH_nxp-s32g-layer = "${LAYERDIR}"

WRL_RECIPES:wr-nxp-s32g += " \
    atf-s32g \
    atf-s32g-tools \
    ipc-shm \
    libfci \
    libfci-cli \
    pfe \
    pfe-slave \
    pkcs11-hse \
    pkcs11-hse-examples \
    u-boot-s32 \
    u-boot-tools \
    optee-os \
    optee-os-tadevkit \
    optee-test \
    optee-client \
    optee-examples \
"
